services:
  server:
    build:
      context: .
    ports:
      - 8000:5000
#    environment:
#      - POSTGRES_PASSWORD=mysecretpassword
#    depends_on:
#      db:
#        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
#  wkhtmltopdf:
#    image: wkhtmltopdf-ws
#   volumes:
#      - .:/data

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt